### ISSUE TITLE
Export Image Error

### ISSUE THREAD

**Issue by mobilome** [evolgeniusteam/evolivew-local-deploy#1]
Hi,
I got an error (Oops... an error has occurred, please try again later!!) when I export tree to PNG or PDF, but it's ok to export to Newick.
Is there a way to solve this problem?

Thank you in advance,

Naisu

**Comment by balaram26** [comment]
Hi can you give us more information?  i like to know the size of your tree file, and may be you can share the tree with us? in general i check the functionalities, they seem to work the normal way. so if you could provide us with more info, i can try replicating the issue and see what's causing this error for you.

Thank you,
Evolview Team

**Comment by mobilome** [comment]
Hi, i failed to share the picture and tree file in the Issue, so could  you give me your email address?  I can send the more information about this error to you by email.
Thank you，
Naisu

**Comment by balaram26** [comment]
Hi, sure you can use send us the details to [evolgenius.team@gmail.com](evolgenius.team@gmail.com).
Thank you,
Evolview Team

**Comment by golikp** [comment]
I have the same problem. Any image export from the "Export" tab fails. For PDF I get just an empty document, for anything else (tiff, png, etc.) after I click the download link I get:
```
HTTP Status 404 – Not Found
Type Status Report
Message The requested resource [/evolview/userfiles/3fe064307b7f19d6.jpeg] is not available
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/9.0.70 (Debian)
```
This is independent of the tree size or complexity (tried with a tree with just 10 species). Only SVG export from the "Basic" tab works. Exporting text formats (newick, nexus, xml) from the "Export" tabs works, but not images.

**Comment by golikp** [comment]
This might be relevant. Here's the error message in catalina.2023-12-28.log

```
28-Dec-2023 16:40:26.529 SEVERE [https-openssl-nio-443-exec-2] org.evolview.server.GWTServiceImpl.exportTreeImage null
	org.apache.batik.transcoder.TranscoderException: Error while setting up PDFDocumentGraphics2D
Enclosed Exception:
Error while setting up fonts
		at org.apache.fop.svg.PDFTranscoder.transcode(PDFTranscoder.java:136)
		at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
		at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
		at org.evolview.server.GWTServiceImpl.exportTreeImage(GWTServiceImpl.java:488)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
		at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:696)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.evolview.server.GWTCacheControlFilter.doFilter(GWTCacheControlFilter.java:38)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by golikp** [comment]
I have found a solution. It's related to the FOP java subsystem looking for /var/lib/tomcat and not finding it. Just do (as root)
`ln -s /var/lib/tomcat9 /var/lib/tomcat`
(substitute "tomcat9" for the version you have installed). Now every export works.
